### ISSUE TITLE
running failure!

### ISSUE THREAD

**Issue by 250444444** [karthikswarna/Extended-code2vec-model#1]
Hi,guys, I got an error,and cannot fix it. 
![image](https://user-images.githubusercontent.com/39322221/144194660-f24fc714-d78d-4778-9510-3a8ef33ca2d4.png)
The tensorflow version is 2.0.0, about  version of 2.0.0-beta1 i cannot find it. Is this  the reasion?

**Comment by karthikswarna** [comment]
Seems like the _steps_per_epoch_ is not initialized properly. 
Can you tell me the number of samples in your dataset and the TRAIN_BATCH_SIZE parameter in _config.py_ file?
